In [1]:
import numpy as np

In [10]:
# All 0s matrix
# np.zeros(shape)
# np.zeros(5)
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# All 1s Matrix
np.ones((4,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [15]:
# Any antoher
np.full((2,3),111,dtype='float32')

array([[111., 111., 111.],
       [111., 111., 111.]], dtype=float32)

In [20]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [22]:
print(np.full_like(a,9))

[[9 9 9 9 9]
 [9 9 9 9 9]]


In [26]:
# Random Decimal Numbers
np.random.rand(4,3)

array([[0.65076801, 0.47184357, 0.2727974 ],
       [0.67594327, 0.49462701, 0.14536295],
       [0.36626017, 0.01774483, 0.34398153],
       [0.28559221, 0.24418551, 0.50837468]])

In [27]:
np.random.random_sample(a.shape)

array([[0.32053559, 0.56828096, 0.30249537, 0.62908742, 0.45246434],
       [0.96616291, 0.45355652, 0.96054174, 0.97172151, 0.58646164]])

In [29]:
# Random Integrer vluaes
np.random.randint(7,size = (3,3))

array([[3, 6, 0],
       [2, 2, 0],
       [0, 5, 6]], dtype=int32)

In [31]:
# Identity matrix : Diagonally all are one(1) and rest of the cell are 0
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [42]:
# fill the middle element of the matrix  = 9 and the all side element  = 1 and rest of the element will be become 0

output = np.ones((5,5))
print(output)

# make the 3,3 matrix
zero = np.zeros((3,3))
print(zero)

# initilize the midle = 9
zero[1,1] = 9
print(zero)

# Now make the full matrix
output[1:4, 1:4] = zero
print("Final Matrix\n",output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
Final Matrix
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copy Array

In [ ]:
a = np.array([1,2,3])
b = a.copy() # Can't use b = a & b[1] = 10.
b[1] = 10
print(a)
print(b)

[1 2 3]
[ 1 10  3]
