# Linear Algebra

In [1]:
import numpy as np

In [4]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [5]:
# Matrix Multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [7]:
# Find the determinate
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)