# Mathematics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a + 2

array([5, 6, 7, 8])

In [5]:
a - 2

array([1, 2, 3, 4])

In [6]:
a * 2

array([ 6,  8, 10, 12])

In [7]:
a / 2

array([1.5, 2. , 2.5, 3. ])

In [8]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [9]:
a ** 2

array([ 9, 16, 25, 36])

In [12]:
# Take the Sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [14]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])