# Accessing / Changing Specific Elements, row, columns

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# Get a specific element [row, col]
#a[1,4]
a[-1,4]

np.int64(10)

In [8]:
# Get a specific row
print(a[0,:])
print(a[1,:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [9]:
# Get specific column
a[:,2]

array([3, 8])

In [14]:
# Getting a little more fancy [startIdx : endidx : stepsize]
a[0, 1:6:1]

array([2, 3, 4, 5])

In [21]:
# Specific row or col replace
a[0,4] = 10
print(a)

a[:, 2] = [100,200]
print(a)

[[  1   2 100   4  10]
 [  6   7 200   9  10]]
[[  1   2 100   4  10]
 [  6   7 200   9  10]]
