In [2]:
import numpy as np

# The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# Get the Dimension
print(a.ndim)
print(b.ndim)

1
2


In [9]:
# Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [10]:
# Get type
print(a.dtype)
print(b.dtype)

int64
int64


In [12]:
# Get size
a.itemsize

8

In [15]:
# Get total Size
a.nbytes

24